SELECT p.PRODUCT_ID, p.PRODUCT_NAME, SUM((o.AMOUNT*p.PRICE)) TOTAL_SALES 
FROM FOOD_PRODUCT p JOIN FOOD_ORDER o
ON p.PRODUCT_ID = o.PRODUCT_ID
WHERE PRODUCE_DATE LIKE '2022-05%'
GROUP BY PRODUCT_ID, PRODUCT_NAME
ORDER BY 3 DESC, 1