WITH OrderedStations AS (
    SELECT ROW_NUMBER() OVER (ORDER BY LAT_N) AS ROW_NUM, LAT_N
    FROM STATION
)
SELECT ROUND(LAT_N, 4)
FROM OrderedStations
WHERE ROW_NUM = (SELECT FLOOR(AVG(ROW_NUM)) FROM OrderedStations);