ALTER TABLE CITY
ADD DIFFERENCE INT;

UPDATE CITY
SET DIFFERENCE = (SELECT max_t - min_t
                  FROM (SELECT MAX(POPULATION) AS max_t, MIN(POPULATION) AS min_t FROM CITY) AS temp);

SELECT DISTINCT(DIFFERENCE) FROM CITY;
