SELECT CAR_ID FROM (SELECT c.CAR_ID, c.CAR_TYPE, h.START_DATE
                    FROM CAR_RENTAL_COMPANY_CAR c
                    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h
                    ON c.CAR_ID = h.CAR_ID) f
WHERE DATE_FORMAT(START_DATE, "%m") = 10 AND CAR_TYPE = '세단'
GROUP BY CAR_ID
ORDER BY CAR_ID DESC