SELECT f.CATEGORY, f.PRICE, f.PRODUCT_NAME FROM FOOD_PRODUCT f 
JOIN (SELECT CATEGORY, MAX(PRICE) PRICE FROM FOOD_PRODUCT 
      GROUP BY CATEGORY) s 
ON f.CATEGORY = s.CATEGORY AND f.PRICE = s.PRICE
WHERE f.CATEGORY IN ('과자','국','김치','식용유')
ORDER BY f.PRICE DESC