WITH ConcatTable AS (SELECT VIEWS, FILE_ID, CONCAT('/home/grep/src/', b.BOARD_ID, '/', f.FILE_ID, f.FILE_NAME, f.FILE_EXT) FILE_PATH 
FROM USED_GOODS_BOARD b JOIN USED_GOODS_FILE f
ON b.BOARD_ID = f.BOARD_ID)
SELECT FILE_PATH
FROM ConcatTable
WHERE VIEWS = (SELECT MAX(VIEWS) FROM ConcatTable
               )
ORDER BY FILE_ID DESC