SELECT t2.FLAVOR 
FROM (
    SELECT t1.FLAVOR, SUM(t1.TOTAL_ORDER) AS SUM_TOTAL_ORDER 
    FROM (
        SELECT h.FLAVOR, h.TOTAL_ORDER 
        FROM FIRST_HALF h 
        JOIN JULY j ON h.FLAVOR = j.FLAVOR
    ) t1
    GROUP BY t1.FLAVOR
    ORDER BY SUM_TOTAL_ORDER DESC
    LIMIT 3
) t2;
