SELECT * 
FROM CAR_RENTAL_COMPANY_CAR
WHERE 
    SUBSTRING_INDEX(SUBSTRING_INDEX(OPTIONS, ',', 1), ',', -1) = '네비게이션' OR
    SUBSTRING_INDEX(SUBSTRING_INDEX(OPTIONS, ',', 2), ',', -1) = '네비게이션' OR
    SUBSTRING_INDEX(SUBSTRING_INDEX(OPTIONS, ',', 3), ',', -1) = '네비게이션' OR
    SUBSTRING_INDEX(SUBSTRING_INDEX(OPTIONS, ',', 4), ',', -1) = '네비게이션' OR
    SUBSTRING_INDEX(SUBSTRING_INDEX(OPTIONS, ',', 5), ',', -1) = '네비게이션' OR
    SUBSTRING_INDEX(SUBSTRING_INDEX(OPTIONS, ',', 6), ',', -1) = '네비게이션' OR
    SUBSTRING_INDEX(SUBSTRING_INDEX(OPTIONS, ',', 7), ',', -1) = '네비게이션'
ORDER BY CAR_ID DESC
